In [53]:
import pandas as pd
import numpy as np
import sklearn

In [54]:
data  = pd.read_csv('data/bank-full.csv',  sep=';')

In [55]:
data

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,no,cellular,17,nov,977,3,-1,0,unknown,yes
45207,71,retired,divorced,primary,no,1729,no,no,cellular,17,nov,456,2,-1,0,unknown,yes
45208,72,retired,married,secondary,no,5715,no,no,cellular,17,nov,1127,5,184,3,success,yes
45209,57,blue-collar,married,secondary,no,668,no,no,telephone,17,nov,508,4,-1,0,unknown,no
45210,37,entrepreneur,married,secondary,no,2971,no,no,cellular,17,nov,361,2,188,11,other,no

In [56]:
data = data[['age',
'job',
'marital',
'education',
'balance',
'housing',
'contact',
'day',
'month',
'duration',
'campaign',
'pdays',
'previous',
'poutcome',
'y']]

In [57]:
data

,age,job,marital,education,balance,housing,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,2143,yes,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,29,yes,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,2,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,1506,yes,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,1,no,unknown,5,may,198,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,825,no,cellular,17,nov,977,3,-1,0,unknown,yes
45207,71,retired,divorced,primary,1729,no,cellular,17,nov,456,2,-1,0,unknown,yes
45208,72,retired,married,secondary,5715,no,cellular,17,nov,1127,5,184,3,success,yes
45209,57,blue-collar,married,secondary,668,no,telephone,17,nov,508,4,-1,0,unknown,no
45210,37,entrepreneur,married,secondary,2971,no,cellular,17,nov,361,2,188,11,other,no

In [58]:
data.education.mode()

0    secondary
Name: education, dtype: object

In [59]:
data.replace(['?', 'хз', 'unknown', 'н/д'], np.nan, inplace=True)

C:\Users\admin\AppData\Local\Temp\ipykernel_8092\751429164.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.replace(['?', 'хз', 'unknown', 'н/д'], np.nan, inplace=True)

In [60]:
data.isna().sum()

age              0
job            288
marital          0
education     1857
balance          0
housing          0
contact      13020
day              0
month            0
duration         0
campaign         0
pdays            0
previous         0
poutcome     36959
y                0
dtype: int64

In [61]:
corr = data.corr(numeric_only=True)

In [62]:
corr

               age   balance       day  duration  campaign     pdays  previous
age       1.000000  0.097783 -0.009120 -0.004648  0.004760 -0.023758  0.001288
balance   0.097783  1.000000  0.004503  0.021560 -0.014578  0.003435  0.016674
day      -0.009120  0.004503  1.000000 -0.030206  0.162490 -0.093044 -0.051710
duration -0.004648  0.021560 -0.030206  1.000000 -0.084570 -0.001565  0.001203
campaign  0.004760 -0.014578  0.162490 -0.084570  1.000000 -0.088628 -0.032855
pdays    -0.023758  0.003435 -0.093044 -0.001565 -0.088628  1.000000  0.454820
previous  0.001288  0.016674 -0.051710  0.001203 -0.032855  0.454820  1.000000

In [63]:
np.fill_diagonal(corr.values, np.nan)

In [64]:
corr.stack().idxmax()

('pdays', 'previous')

In [65]:
data['y'] = data['y'].replace({'yes': 1, 'no': 0})

C:\Users\admin\AppData\Local\Temp\ipykernel_8092\728656230.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['y'] = data['y'].replace({'yes': 1, 'no': 0})
C:\Users\admin\AppData\Local\Temp\ipykernel_8092\728656230.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['y'] = data['y'].replace({'yes': 1, 'no': 0})

In [66]:
data

,age,job,marital,education,balance,housing,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,2143,yes,NaN,5,may,261,1,-1,0,NaN,0
1,44,technician,single,secondary,29,yes,NaN,5,may,151,1,-1,0,NaN,0
2,33,entrepreneur,married,secondary,2,yes,NaN,5,may,76,1,-1,0,NaN,0
3,47,blue-collar,married,NaN,1506,yes,NaN,5,may,92,1,-1,0,NaN,0
4,33,NaN,single,NaN,1,no,NaN,5,may,198,1,-1,0,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,825,no,cellular,17,nov,977,3,-1,0,NaN,1
45207,71,retired,divorced,primary,1729,no,cellular,17,nov,456,2,-1,0,NaN,1
45208,72,retired,married,secondary,5715,no,cellular,17,nov,1127,5,184,3,success,1
45209,57,blue-collar,married,secondary,668,no,telephone,17,nov,508,4,-1,0,NaN,0
45210,37,entrepreneur,married,secondary,2971,no,cellular,17,nov,361,2,188,11,other,0

In [67]:
from sklearn.model_selection import train_test_split
X = data.drop('y', axis=1)
y = data['y']

# Первое разделение: 60% тренировочные, 40% временные (для валидации и теста)
X_train, X_temp, y_train, y_temp = train_test_split(X, y,test_size=0.4,       random_state=42,stratify=y)

In [68]:
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp,test_size=0.5,random_state=42,stratify=y_temp)

In [69]:
cat_cols = ['job', 'marital', 'education', 'housing', 'contact', 'month', 'poutcome']
X_train_cat = X_train[cat_cols].fillna('missing')
from sklearn.feature_selection import mutual_info_classif
mi_scores = mutual_info_classif(
    pd.get_dummies(X_train_cat),
    y_train,
    random_state=42)

In [70]:
mi = pd.Series(mi_scores, index=pd.get_dummies(X_train_cat).columns)

In [71]:
mi_per_feature = mi.groupby(lambda c: c.split('_')[0]).mean().round(2)
print("MI per feature:\n", mi_per_feature)
print("Максимальная взаимная информация у:", mi_per_feature.idxmax())

MI per feature:
 contact      0.01
education    0.00
housing      0.01
job          0.00
marital      0.00
month        0.00
poutcome     0.01
dtype: float64
Максимальная взаимная информация у: contact

In [72]:
X_train_enc = pd.get_dummies(X_train.fillna('missing'))
X_val_enc = pd.get_dummies(X_val.fillna('missing'))

In [73]:
X_val_enc = X_val_enc.reindex(columns=X_train_enc.columns, fill_value=0)

In [74]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
model.fit(X_train_enc, y_train)
val_pred = model.predict(X_val_enc)
acc = round(accuracy_score(y_val, val_pred), 2)

In [75]:
acc

0.9

In [76]:
base_acc = acc
diffs = {}

for col in X_train_enc.columns:
    X_train_sub = X_train_enc.drop(columns=[col])
    X_val_sub = X_val_enc.drop(columns=[col])

    m = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
    m.fit(X_train_sub, y_train)
    acc_sub = accuracy_score(y_val, m.predict(X_val_sub))
    diffs[col] = base_acc - acc_sub

diffs_series = pd.Series(diffs)
min_diff_feature = diffs_series.abs().idxmin()

Наименее значимый признак: housing_yes

In [77]:
min_diff_feature

'housing_yes'

In [78]:
for c in [0.01, 0.1, 1, 10, 100]:
    m = LogisticRegression(solver='liblinear', C=c, max_iter=1000, random_state=42)
    m.fit(X_train_enc, y_train)
    pred = m.predict(X_val_enc)
    score = round(accuracy_score(y_val, pred), 3)

In [79]:
print(f"C={c}: accuracy={score}")

C=100: accuracy=0.9

1)secondary

2)pdays и previous

3)contact

4)0.9

5)housing_yes

6)100